### ISSUE TITLE
OpenAL on Windows

### ISSUE THREAD

**Issue by itayadler** [Burgestrand/hallon-openal#4]
anyone managed to install Hallon-OpenAL on windows?

**Comment by Burgestrand** [comment]
I haven’t heard of anyone trying it out, nor have I received questions about it previously. Last time I tried the spotify gem on windows, which is almost one or two years ago, FFI did not find the functions in libspotify to bind to them. With that said, I would not expect any of the gems (spotify, hallon, hallon-openal) to work on windows, but I have not tried it myself.

Given this is not an actual issue, I’ll close this. If you wish to continue the discussion you’re welcome to do so on the mailing list: https://groups.google.com/forum/#!forum/ruby-hallon

**Comment by itayadler** [comment]
Thanks for the quick response, I'll try to ask in the google group :)
